Endpoints
Pauliski/ride_my_way-backend pull request #6
Opened 2021-06-22 11:53 UTC by Pauliski

2021-06-22 14:02 UTC, nosisky commented on src/controllers/DriverController.js
> +    const { first_name, last_name, gender, mobile_number, car_plate, image_url, email, password, car_url } = req.body;
Your request body should not use snake casing, data should be sent as camel case.

2021-06-22 14:03 UTC, nosisky commented on src/controllers/DriverController.js
> +      const token = jwt.sign({
Can you abstract this into a helper function so you can reuse it since you also need something similar for the user signup?

2021-06-22 14:04 UTC, nosisky commented on src/controllers/DriverController.js
> +   const {error} = driversUpdateProfileValidation(req.body)
THis should be called with a middleware and not inside the controller file.

2021-06-22 14:05 UTC, nosisky commented on src/controllers/PassengerController.js
> +console.log({secretKey}, '---->')
Take this out, you should not push code with console statements online unless absolutely necessary.

2021-06-22 14:06 UTC, nosisky commented on src/controllers/PassengerController.js
> +      const token = jwt.sign({
Just as I said before, this jwt logic should be abstracted into a function so you don't have to repeat yourself.

2021-06-22 14:08 UTC, nosisky commented on src/models/model.js
> +  if(datas){                                                    // datas ={destination: "Isolo", amount: 500}
should be data not datas

2021-06-22 14:09 UTC, nosisky commented on src/routes/index.js
> +indexRouter.get('/passengers', passengersPage);
I highly suggest the routes should be moved into a separate file for every module. e.g driver route should be in a separate file, user route separate file etc.

2021-06-22 14:11 UTC, nosisky commented on src/controllers/PassengerController.js
> +    const passengerExists = await passengersModel.select('id, email, first_name, login_status', `WHERE "email" = '${email}'`);
There is really not a need for this logic unless you need it somewhere.

2021-06-22 14:12 UTC, nosisky commented on src/controllers/PassengerController.js
> +    const token = jwt.sign({
Why are you signing the token again?

2021-06-29 07:32 UTC, nosisky commented on src/controllers/RideHistoryController.js
> +    res.status(200).json({ History: data.rows });
This should be history and not History

2021-06-29 07:33 UTC, nosisky commented on src/controllers/RideHistoryController.js
> +    res.status(200).json({ History: err.stack });
This is error, it should be error and not History since it denotes that something went wrong.

2021-06-29 07:34 UTC, nosisky commented on src/controllers/RideHistoryController.js
> +    const data = await rideHistoryModel.select('drivers_id, destination, amount, created_at, status', `WHERE "passengers_id" = '${id}'`);
passenger_id not passengers_id, it represents a single entity.

2021-06-29 07:35 UTC, nosisky commented on src/controllers/PassengerController.js
> +  console.log(req.user);
Take away this console statement.

2021-06-29 07:35 UTC, nosisky commented on src/controllers/PassengerController.js
> +    const signedToken = SignToken(passenger);
Great work on implementing this feedback but a function name in Javascript should be camelcase and not PascalCase.

2021-06-29 07:37 UTC, nosisky commented on src/controllers/OfferController.js
> +    res.status(500).json({ Offers: err.stack });
This should be error and not Offers

2021-06-29 07:37 UTC, nosisky commented on src/controllers/OfferController.js
> +    res.status(500).json({ Offers: err.stack });
error, not Offers

2021-06-29 09:39 UTC, nosisky commented on src/controllers/PassengerController.js
> +    console.log(error.message);
Return the actual response.

2021-06-30 13:00 UTC, Pauliski commented on src/controllers/DriverController.js
> +      status: 'failed'
I don't understand this

2021-06-30 15:33 UTC, nosisky commented
Thanks for taking time to address the feedback so far.

2021-07-01 15:41 UTC, nosisky requested changes

2021-07-01 15:41 UTC, nosisky commented on src/routes/OffersRoute.js
> +offersRoute.delete('/offer/delete/:id', isLoggedIn, deleteOffer);
There is no need for delete in the route again, the method name is already `delete`.

2021-07-01 15:41 UTC, nosisky commented on src/routes/OffersRoute.js
> +offersRoute.put('/offer/edit/:id', isLoggedIn, updateOffer);
There is no need for edit in the route again, the method name is already `put`.

2021-07-01 15:41 UTC, nosisky commented on src/controllers/OfferController.js
> +    return res.status(200).json({ Offers: data.row, success: true });
Should be `offers` not Offers

2021-07-01 15:41 UTC, nosisky commented on src/controllers/OfferController.js
> +    return res.status(200).json({ Offers: data.rows });
offers not `Offers`

2021-07-06 00:38 UTC, johnkingzy commented on package.json
>      "mocha": "^8.4.0",
Is mocha not suppose to be a devDependency?

2021-07-06 00:39 UTC, johnkingzy commented on package.json
>      "nodemon": "^2.0.7",
Do you also need nodemon in production? Is this not suppose to be a devDependency as well

2021-07-06 00:39 UTC, johnkingzy commented on package.json
>      "prettier": "^2.3.0",
Same as prettier, why do you need this in production?

2021-07-06 00:39 UTC, johnkingzy commented on package.json
>      "sinon-chai": "^3.7.0",
Same as this??

2021-07-06 00:40 UTC, johnkingzy commented on package.json
>      "supertest": "^6.1.3"
Same as this as well?

2021-07-06 00:40 UTC, johnkingzy commented on src/app.js
> +/* eslint-disable import/extensions */
Why are you disabling eslint here? can you modify the eslint rule to support this feature instead?

2021-07-06 00:41 UTC, johnkingzy commented on src/controllers/DriverController.js
> + * @description - Addnew driver
Looks like the descriptions doesn't match the function purpose

2021-07-06 00:42 UTC, johnkingzy commented on src/controllers/DriverController.js
> + * @return {Object} -
Nitpick: no description

2021-07-06 00:43 UTC, johnkingzy commented on src/controllers/DriverController.js
> +    return res.status(200).json({
I think https status code `201` would be ideal for this case

2021-07-06 00:45 UTC, johnkingzy commented on src/controllers/OfferController.js
> +    return res.status(200).json({ offers: data.rows });
I think https status code `201` would be ideal for this case

2021-07-06 00:45 UTC, johnkingzy commented on src/controllers/OfferController.js
> +    return res.status(200).json({ offers: data.rows });
You can read more about http status code here
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

2021-07-06 00:47 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +  const { email, mobileNumber } = req.body;
Can we validate the email format before running a query with it? This is a security leak, your app is prone to SQL Injection

2021-07-06 00:47 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +  const { email, mobileNumber } = req.body;
Please do this everywhere where you are grabbing email from the user inputs

2021-07-06 00:48 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +      return res.status(400).send({
If email already I think the ideal status is `409` - Conflicts

Read more status code here
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

2021-07-06 00:49 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +      .select('id, email, password', `WHERE "email" = '${email}'`);
Email format validation ??? same as comment above

2021-07-06 00:49 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +      return res.status(400).send({
If the record matching the email doesn't exists, I think the appropriate status code is 404

2021-07-06 02:32 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +  const { email, mobileNumber } = req.body;
Please ignore this if you are already doing this with the validator middleware 👍

2021-07-06 02:32 UTC, johnkingzy commented on src/middleware/AuthMiddleware.js
> +      return res.status(400).send({
I'd suggest `409` instead - Conflict

2021-07-06 02:35 UTC, johnkingzy requested changes
Overall, very well done!

2021-07-23 12:40 UTC, merged